default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: skracacz_test_1_development

test:
  <<: *default
  database: skracacz_test_1_test

production:
  <<: *default
  database: skracacz_test_1_production
  username: skracacz_test_1
  password: <%= ENV['SKRACACZ_TEST_1_DATABASE_PASSWORD'] %>
